require "json"
require "yaml"
require "log"

require "./lsp_crystal/version"
require "./lsp_crystal/logger"
require "./lsp_crystal/protocol/types"
require "./lsp_crystal/protocol/uri"
require "./lsp_crystal/jsonrpc/types"
require "./lsp_crystal/jsonrpc/message"
require "./lsp_crystal/transport/header_parser"
require "./lsp_crystal/transport/stdio"
require "./lsp_crystal/document_store"
require "./lsp_crystal/cancellation_token"
require "./lsp_crystal/request_tracker"
require "./lsp_crystal/crystal_tool"
require "./lsp_crystal/ast/parser"
require "./lsp_crystal/ast/cache"
require "./lsp_crystal/ast/indexed_symbol"
require "./lsp_crystal/ast/lexer_tokenizer"
require "./lsp_crystal/providers/macro_expander"
require "./lsp_crystal/ast/visitors/symbol_visitor"
require "./lsp_crystal/ast/visitors/reference_visitor"
require "./lsp_crystal/ast/visitors/context_visitor"
require "./lsp_crystal/ast/visitors/call_visitor"
require "./lsp_crystal/ast/visitors/index_visitor"
require "./lsp_crystal/ast/index"
require "./lsp_crystal/providers/diagnostics"
require "./lsp_crystal/providers/formatting"
require "./lsp_crystal/providers/definition"
require "./lsp_crystal/providers/hover"
require "./lsp_crystal/providers/completion"
require "./lsp_crystal/providers/document_symbol"
require "./lsp_crystal/providers/workspace_symbol"
require "./lsp_crystal/providers/signature_help"
require "./lsp_crystal/providers/document_highlight"
require "./lsp_crystal/providers/folding_range"
require "./lsp_crystal/providers/selection_range"
require "./lsp_crystal/providers/implementation"
require "./lsp_crystal/providers/references"
require "./lsp_crystal/providers/code_action"
require "./lsp_crystal/providers/rename"
require "./lsp_crystal/providers/type_definition"
require "./lsp_crystal/providers/semantic_tokens"
require "./lsp_crystal/providers/call_hierarchy"
require "./lsp_crystal/providers/inlay_hints"
require "./lsp_crystal/providers/code_lens"
require "./lsp_crystal/providers/linked_editing_range"
require "./lsp_crystal/providers/type_hierarchy"
require "./lsp_crystal/workspace_index"
require "./lsp_crystal/require_graph"
require "./lsp_crystal/configuration"
require "./lsp_crystal/handlers/lifecycle"
require "./lsp_crystal/handlers/text_sync"
require "./lsp_crystal/handlers/formatting"
require "./lsp_crystal/handlers/definition"
require "./lsp_crystal/handlers/hover"
require "./lsp_crystal/handlers/completion"
require "./lsp_crystal/handlers/document_symbol"
require "./lsp_crystal/handlers/workspace_symbol"
require "./lsp_crystal/handlers/signature_help"
require "./lsp_crystal/handlers/document_highlight"
require "./lsp_crystal/handlers/folding_range"
require "./lsp_crystal/handlers/selection_range"
require "./lsp_crystal/handlers/implementation"
require "./lsp_crystal/handlers/references"
require "./lsp_crystal/handlers/code_action"
require "./lsp_crystal/handlers/rename"
require "./lsp_crystal/handlers/type_definition"
require "./lsp_crystal/handlers/semantic_tokens"
require "./lsp_crystal/handlers/call_hierarchy"
require "./lsp_crystal/handlers/inlay_hints"
require "./lsp_crystal/handlers/code_lens"
require "./lsp_crystal/handlers/linked_editing_range"
require "./lsp_crystal/handlers/type_hierarchy"
require "./lsp_crystal/handlers/configuration"
require "./lsp_crystal/handlers/workspace_folders"
require "./lsp_crystal/handlers/did_change_watched_files"
require "./lsp_crystal/dispatcher"
require "./lsp_crystal/server"

module Lsp::Crystal
  def self.run
    setup_logging
    server = Server.new
    server.run
  end
end

Lsp::Crystal.run
